package com.fa20se28.vma.enums;

public enum ReportType {
    VEHICLES,
    SCHEDULE,
    MAINTENANCE,
    MAINTENANCE_ALL_VEHICLES,
    CONTRACTS,
    VEHICLE_REVENUE_EXPENSE,
    COMPANY_REVENUE_EXPENSE,
    CONTRIBUTOR_INCOMES,
    CONTRIBUTORS_INCOMES,
}
