package com.fa20se28.vma.enums;

public enum RequestType {
    NEW_DOCUMENT,
    UPDATE_DOCUMENT,
    DELETE_DOCUMENT,
    NEW_VEHICLE_DOCUMENT,
    DELETE_VEHICLE_DOCUMENT,
    CHANGE_VEHICLE,
    VEHICLE_NEEDS_REPAIRED,
    NEED_BACKUP_VEHICLE,
    ADD_NEW_VEHICLE,
    WITHDRAWAL_VEHICLE
}
